# Sử dụng hình ảnh .NET Core để build
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["shopsport/shopsport.csproj", "shopsport/"]
RUN dotnet restore "shopsport/shopsport.csproj"
COPY . .
WORKDIR "/src/shopsport"
RUN dotnet build "shopsport.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "shopsport.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "shopsport.dll"]
EXPOSE 80
